"""gps_analysis — general GNSS time-series analysis for the IMO network.

Leaf math package (Tier 1) of the gpslibrary ecosystem: trajectory models,
robust detrending, velocity estimation (WLS → colored-noise MLE), baseline
utilities, and deformation-source inversion (Mogi → Okada → joint GPS+InSAR).

Consolidates the proven analysis code from ``~/work/projects/gps_data_analyses``
(``svartsengi-model``, the ``detrend-*`` family) into small, pure, unit-agnostic,
tested functions. Module plan: PLAN-postprocessing-revamp.md §10.2 in the
gpslibrary_new collection.

Dependency policy (hard rule, plan risk R6): numpy / scipy / gtimes only —
this package must never import geo_dataread, gps_parser, tostools, receivers,
gps_plot or gps_api.
"""

__version__ = "0.1.0"

from gps_analysis.baseline import (
    estimate_offset,
    estimate_step_offset,
    remove_offset,
    slice_window,
)
from gps_analysis.deformation import (
    FaultPatches,
    MogiFit,
    MogiPosterior,
    MogiSource,
    OkadaFit,
    OkadaSource,
    SlipDistribution,
    discretize_fault,
    halflife_days,
    lcurve_corner,
    local_coordinates,
    mogi_forward,
    mogi_invert,
    mogi_invert_bayes,
    mogi_mctigue,
    okada_forward,
    okada_greens,
    okada_invert,
    okada_invert_slip,
    patch_laplacian,
    pressure_from_volume,
    rate_from_m3s,
    rate_to_m3s,
    slip_lcurve,
    time_for_rate,
    volume_from_pressure,
)
from gps_analysis.detrend import (
    DETREND_METHOD_PLAIN,
    DETREND_METHOD_ROBUST,
    DetrendEstimate,
    apply_detrend,
    estimate_detrend,
    evaluate_record,
    select_terms,
    trajectory_from_record,
)
from gps_analysis.fitting import (
    ModelFunc,
    OutlierRejection,
    detrend_fit,
    fit_components,
    reject_outliers,
    remove_trend,
    with_steps,
)
from gps_analysis.joint import (
    InsarLos,
    JointFit,
    los_project,
    los_unit_vector,
    mogi_invert_joint,
    param_correlation,
    ramp_design,
    variance_components,
)
from gps_analysis.models import (
    FloatArray,
    TrajectoryParams,
    exp_linear,
    exp_linear_rate,
    heaviside_steps,
    linear,
    lineperiodic,
    periodic,
    poly2,
    poly2_peak_time,
    poly2_peak_value,
    poly2_rate,
)
from gps_analysis.noise import (
    NoiseMLEFit,
    NoiseModel,
    estimate_noise_mle,
    powerlaw_rate_sigma,
)
from gps_analysis.outliers import (
    PROTECT_FLOOR,
    PROTECT_RUN,
    PROTECT_STEP,
    PROTECT_WINDOW,
    REASON_GLOBAL,
    REASON_GROSS,
    REASON_LOCAL,
    OutlierDetection,
    OutlierParams,
    SuspectedEvent,
    candidate_clusters,
    detect_outliers,
    hampel_mask,
    mad_scale,
    neighbor_differences,
    qn_scale,
    rolling_mad,
    rolling_median,
    rolling_polyfit,
    spike_mask,
    standardize_robust,
    step_evidence,
    whiten,
)
from gps_analysis.preprocess import (
    prep_neu_series,
    prep_plot_series,
    screen_uncertainty,
)
from gps_analysis.transient import (
    BPD1Params,
    BPD2Params,
    InversionConfig,
    InversionResult,
    PriorBounds,
    bpd1_forward,
    bpd2_forward,
    detect_breakpoints,
    log_likelihood,
    noise_covariance,
    prepare_bounds,
    run_inversion,
)
from gps_analysis.velocity import (
    SlidingVelocity,
    VelocityEstimate,
    VelocityEstimateMLE,
    detectability_floor,
    estimate_velocity,
    estimate_velocity_mle,
    horizontal_azimuth,
    horizontal_azimuth_sigma,
    horizontal_magnitude,
    horizontal_magnitude_sigma,
    sliding_velocity,
)

__all__ = [
    "__version__",
    # models
    "FloatArray",
    "TrajectoryParams",
    "linear",
    "periodic",
    "lineperiodic",
    "exp_linear",
    "exp_linear_rate",
    "heaviside_steps",
    "poly2",
    "poly2_rate",
    "poly2_peak_time",
    "poly2_peak_value",
    # fitting
    "ModelFunc",
    "OutlierRejection",
    "fit_components",
    "detrend_fit",
    "remove_trend",
    "reject_outliers",
    "with_steps",
    # outliers (model-aware detection + signal protection)
    "REASON_GLOBAL",
    "REASON_GROSS",
    "REASON_LOCAL",
    "PROTECT_FLOOR",
    "PROTECT_RUN",
    "PROTECT_STEP",
    "PROTECT_WINDOW",
    "OutlierParams",
    "OutlierDetection",
    "SuspectedEvent",
    "mad_scale",
    "qn_scale",
    "whiten",
    "standardize_robust",
    "neighbor_differences",
    "spike_mask",
    "rolling_median",
    "rolling_mad",
    "rolling_polyfit",
    "hampel_mask",
    "candidate_clusters",
    "step_evidence",
    "detect_outliers",
    # detrend (stored-parameter detrending: estimate once, apply anywhere)
    "DETREND_METHOD_PLAIN",
    "DETREND_METHOD_ROBUST",
    "DetrendEstimate",
    "estimate_detrend",
    "select_terms",
    "trajectory_from_record",
    "evaluate_record",
    "apply_detrend",
    # baseline
    "slice_window",
    "estimate_offset",
    "remove_offset",
    "estimate_step_offset",
    # preprocess
    "screen_uncertainty",
    "prep_plot_series",
    "prep_neu_series",
    # velocity
    "VelocityEstimate",
    "VelocityEstimateMLE",
    "SlidingVelocity",
    "estimate_velocity",
    "estimate_velocity_mle",
    "sliding_velocity",
    "horizontal_magnitude",
    "horizontal_azimuth",
    "horizontal_magnitude_sigma",
    "horizontal_azimuth_sigma",
    "detectability_floor",
    # noise (colored-noise MLE)
    "NoiseModel",
    "NoiseMLEFit",
    "estimate_noise_mle",
    "powerlaw_rate_sigma",
    # transient (GBIS4TS)
    "BPD1Params",
    "BPD2Params",
    "PriorBounds",
    "InversionConfig",
    "InversionResult",
    "bpd1_forward",
    "bpd2_forward",
    "noise_covariance",
    "log_likelihood",
    "prepare_bounds",
    "run_inversion",
    "detect_breakpoints",
    # deformation (Mogi / Okada / distributed slip)
    "MogiSource",
    "OkadaSource",
    "MogiFit",
    "OkadaFit",
    "MogiPosterior",
    "FaultPatches",
    "SlipDistribution",
    "local_coordinates",
    "mogi_forward",
    "mogi_mctigue",
    "okada_forward",
    "mogi_invert",
    "mogi_invert_bayes",
    "okada_invert",
    "discretize_fault",
    "okada_greens",
    "patch_laplacian",
    "okada_invert_slip",
    "slip_lcurve",
    "lcurve_corner",
    "pressure_from_volume",
    "volume_from_pressure",
    "rate_to_m3s",
    "rate_from_m3s",
    "time_for_rate",
    "halflife_days",
    # joint GPS + InSAR (LOS projection, VCE, joint Mogi)
    "InsarLos",
    "JointFit",
    "los_unit_vector",
    "los_project",
    "ramp_design",
    "param_correlation",
    "variance_components",
    "mogi_invert_joint",
]
